development:
  :username: 'xxx' 
  :password: 'xxx'
  :customer_number: 'xxx'
  :mode: 'development' 
  
production:  
  :username: 'xxx' 
  :password: 'xxx'
  :customer_number: 'xxx'
  :mode: 'production'